### ISSUE TITLE
Is it possible to run this without port 80/443 being given to this app?

### ISSUE THREAD

**Issue by Leopere** [cloudpatron/cloudpatron#3]
I would prefer to use my existing reverse proxy/load balancer.  Is there tolerance for something else handling these things?

**Comment by onedr0p** [comment]
Use Docker?

**Comment by Leopere** [comment]
I don't recall why that was difficult but typically the first thing I try
when finding a new web app is this.

**Comment by Leopere** [comment]
I'm going to give this another go.  But I need it behind Traefik and not exposed by itself.

**Comment by Pierstoval** [comment]
I have the exact same issue here: even if I use the `-http-addr` option, I can't set it up properly because I have another server running.

IMO, both HTTP and HTTPS ports should be customizable.

Is it something that's easy to set up internally?

**Comment by Leopere** [comment]
At one point I had this working fine.  It collected some payments for me it worked great but I bet its decayed entirely and looks completely abandoned.  It was definitely a nice value add for the internet because decentralization is important to prevent the world from setting into a place of centralized power and opinion.
